sudo: required
services: 
  - docker

before_install:
  - docker build -f danielledelooze/docker-react -f Dockerfile.dev .

script:
  - docker run danielledelooze/docker-react npm run test -- --coverage
